const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

async function sendEmail(to, summary) {
  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background-color:#f4f4f7;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f4f7;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;">
          <tr>
            <td style="background-color:#1a1a2e;padding:24px 32px;">
              <h1 style="margin:0;color:#ffffff;font-size:22px;">Sales Insight Automator</h1>
            </td>
          </tr>
          <tr>
            <td style="padding:32px;">
              <h2 style="color:#1a1a2e;font-size:18px;margin-top:0;">Q1 Sales Insight Summary</h2>
              <div style="color:#333333;font-size:15px;line-height:1.7;white-space:pre-wrap;">${summary}</div>
            </td>
          </tr>
          <tr>
            <td style="background-color:#f4f4f7;padding:20px 32px;text-align:center;">
              <p style="margin:0;color:#888888;font-size:13px;">Generated by Sales Insight Automator</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL,
    to,
    subject: "Q1 Sales Insight Summary",
    html,
  });
}

module.exports = sendEmail;
